version: "3"
services:
    postgres:
        image: postgres:13.1
        container_name: event-sourcing-net-postgres
        environment:
            POSTGRES_PASSWORD: Test1234 
        ports:
            - "5432:5432"
        networks:
            - postgres

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin-container
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
        ports:
            - "${PGADMIN_PORT:-5050}:80"
        networks:
            - postgres

networks:
    postgres:
        driver: bridge

volumes:
    postgres:
        - type: bind
        source: /usr/container_postgres/data
        target: /var/lib/postgresql/data
    pgadmin:
        driver: local